name: build

on:
  push:
    branches:
      - master
    paths:
      - 'src/**/*.scss'
      - 'themes/**/*.scss'
      - 'gulpfile.js'

jobs:
  build:
    name: Rebuild and minify dist assets
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.19.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Update browserslist/caniuse-lite
        run: npx browserslist@latest --update-db

      - name: yarn build
        run: yarn build

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'dist: rebuilt and minified dist assets'
          commit_user_name: loli-bot
          commit_user_email: hi@fiery.me
        env:
          CI: true
